In [2]:
import json, warnings, os
from pathlib import Path

warnings.filterwarnings('ignore')

if Path.cwd().name == "notebooks":
    rootdir = Path.cwd().parent
else:
    rootdir = Path.cwd()
rootdir

PosixPath('/home/gnart/dev/dae/evm-sleuth/examples/OPEN')

In [3]:
import pandas as pd
import plotly.express as px
from plotly import graph_objects as go

from evm_sleuth.utils.postgres import PostgresClient
from evm_sleuth.config import settings

client = PostgresClient(settings.postgres)

import plotly.offline as pyo

pyo.init_notebook_mode(connected=True)

## Primary market

## Mint event

In [8]:
query = """
SELECT 
    chainid,
    token_address,
    from_address,
    to_address,
    amount_hex,
    datetime,
    transaction_hash
FROM 
    staging.erc20_transfer 
WHERE 
    token_address = '0x323c03c48660fe31186fa82c289b0766d331ce21'
    and from_address = '0x0000000000000000000000000000000000000000'
ORDER BY 
    datetime DESC
"""
df = pd.read_sql(query, client.sqlalchemy_engine)
df

,chainid,token_address,from_address,to_address,amount_hex,datetime,transaction_hash
0,1,0x323c03c48660fe31186fa82c289b0766d331ce21,0x0000000000000000000000000000000000000000,0x726e3244e2a73405ce13d82862d81e1c5dd0004e,0x00000000000000000000000000000000000000000000...,2025-08-25 21:17:23+00:00,0x5d61c95f74613e2e50e0fac1002f9014fa4abccdcce5...
1,1,0x323c03c48660fe31186fa82c289b0766d331ce21,0x0000000000000000000000000000000000000000,0x726e3244e2a73405ce13d82862d81e1c5dd0004e,0x00000000000000000000000000000000000000000000...,2025-08-23 04:14:59+00:00,0x32fc2139e0ed5be2ce0f1255a903682273445a20cf3d...
2,1,0x323c03c48660fe31186fa82c289b0766d331ce21,0x0000000000000000000000000000000000000000,0xea9361309f69e22f4b4f49ac4feb7076e3b6c255,0x00000000000000000000000000000000000000000000...,2025-08-22 19:39:35+00:00,0x933aac940c570d3b9421dbd0133de0fba0c29a22a8fe...
3,1,0x323c03c48660fe31186fa82c289b0766d331ce21,0x0000000000000000000000000000000000000000,0x726e3244e2a73405ce13d82862d81e1c5dd0004e,0x00000000000000000000000000000000000000000000...,2025-08-21 12:58:47+00:00,0x63560f8f16351c34abde1c2737a366902edb8044fc35...
4,1,0x323c03c48660fe31186fa82c289b0766d331ce21,0x0000000000000000000000000000000000000000,0x726e3244e2a73405ce13d82862d81e1c5dd0004e,0x00000000000000000000000000000000000000000000...,2025-08-20 19:57:11+00:00,0x52b7c9679a30e99f0f7a46485782b044fbfa699c6750...
...,...,...,...,...,...,...,...
615,1,0x323c03c48660fe31186fa82c289b0766d331ce21,0x0000000000000000000000000000000000000000,0xafd306005f5d1a8537be4960e6d23907b5b9383f,0x00000000000000000000000000000000000000000000...,2025-04-18 20:27:35+00:00,0xaf774981c70f79dc8e37cf9da3fb59d682e830270e63...
616,1,0x323c03c48660fe31186fa82c289b0766d331ce21,0x0000000000000000000000000000000000000000,0xafd306005f5d1a8537be4960e6d23907b5b9383f,0x00000000000000000000000000000000000000000000...,2025-04-18 17:22:11+00:00,0x2fa5c0a407324e6ade99040a7006b152a4a4af28d6bf...
617,1,0x323c03c48660fe31186fa82c289b0766d331ce21,0x0000000000000000000000000000000000000000,0xafd306005f5d1a8537be4960e6d23907b5b9383f,0x00000000000000000000000000000000000000000000...,2025-04-18 17:18:35+00:00,0x97915be7744b4ea73e387e72069d9ad948bea3572da5...
618,1,0x323c03c48660fe31186fa82c289b0766d331ce21,0x0000000000000000000000000000000000000000,0xafd306005f5d1a8537be4960e6d23907b5b9383f,0x00000000000000000000000000000000000000000000...,2025-04-17 19:35:23+00:00,0xd70f765965ffc21a54735a9078b67f2f34a8de774bfa...
619,1,0x323c03c48660fe31186fa82c289b0766d331ce21,0x0000000000000000000000000000000000000000,0x66f66192f91eaa3d48c95ab6bdaf9ade26db06f1,0x00000000000000000000000000000000000000000000...,2025-04-14 19:36:35+00:00,0xa261cf72209e561b3c7956e5a011338b021453eefb35...

In [9]:
df['to_address'].value_counts()

to_address
0xabaebcc9eee363cea2150ee03ac96db110f0e745    200
0xe08d97e151473a848c3d9ca3f323cb720472d015    166
0xafd306005f5d1a8537be4960e6d23907b5b9383f    110
0xea9361309f69e22f4b4f49ac4feb7076e3b6c255     49
0xcbca96091f43c024730a020e57515a18b5dc633b     27
0x2aea77c4757d897aae2710b8a60280777f504e8c     27
0xde3b1a502a6f25b92434a00c4169b195b2f1528c     27
0x726e3244e2a73405ce13d82862d81e1c5dd0004e      6
0x80bf7db69556d9521c03461978b8fc731dbbd4e4      4
0xb3445d5413abf63df1112a4a517de2602f249785      1
0x5895d114a4992f4ce71d61293f7d4fde93fcd695      1
0x00000f91109c4d0007e90000d9facad5298a0cac      1
0x66f66192f91eaa3d48c95ab6bdaf9ade26db06f1      1
Name: count, dtype: int64